# Keras Tutorial

Keras is a popular deep learning framework and it's easy to get started.

In [1]:

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.optimizers import SGD

BATCH_SIZE = 128
NUM_CLASSES = 10
NUM_EPOCHS = 10

Using TensorFlow backend.


First, we read the mnist data and preprocess them.

In [2]:
import ssl
 
ssl._create_default_https_context = ssl._create_unverified_context

# download and load the data (split them between train and test sets)
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# expand the channel dimension
#x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
#x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

x_train = x_train.reshape(60000,784) # 将图片摊平，变成向量
x_test = x_test.reshape(10000,784) # 对测试集进行同样的处理

input_shape = (28, 28, 1)

# make the value of pixels from [0, 255] to [0, 1] for further process
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

print(x_train)

# convert class vectors to binary class matrics
y_train = keras.utils.to_categorical(y_train, NUM_CLASSES)
y_test = keras.utils.to_categorical(y_test, NUM_CLASSES)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Then, we define the model, object function and optimizer that we use to classify.

In [3]:
# define the model
model = Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,)))
model.add(Dense(256,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.summary()

# define the object function, optimizer and metrics
model.compile(optimizer=SGD(),loss='categorical_crossentropy',metrics=['accuracy'])

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


Next, we can start to train and evaluate!

In [4]:
# train
history = model.fit(x_train,y_train,batch_size=64,epochs=20)

# evaluate
score = model.evaluate(x_test,y_test)
H_s = history.history
H_loss = H_s['loss']
H_acc = H_s['accuracy']
print('Training loss: %.4f, Training accuracy: %.2f%%' % (H_loss[19],H_acc[19] * 100))
print('Testing loss: %.4f, Testing accuracy: %.2f%%' % (score[0],score[1] * 100))

Epoch 1/50
60000/60000 [==============================] - 2s 30us/step - loss: 0.7534 - accuracy: 0.8157
Epoch 2/50
60000/60000 [==============================] - 2s 29us/step - loss: 0.3373 - accuracy: 0.9059
Epoch 3/50
60000/60000 [==============================] - 2s 32us/step - loss: 0.2818 - accuracy: 0.9200
Epoch 4/50
60000/60000 [==============================] - 2s 32us/step - loss: 0.2490 - accuracy: 0.9296
Epoch 5/50
60000/60000 [==============================] - 2s 30us/step - loss: 0.2249 - accuracy: 0.9360
Epoch 6/50
60000/60000 [==============================] - 2s 31us/step - loss: 0.2047 - accuracy: 0.9421
Epoch 7/50
60000/60000 [==============================] - 2s 30us/step - loss: 0.1876 - accuracy: 0.9468
Epoch 8/50
60000/60000 [==============================] - 2s 31us/step - loss: 0.1734 - accuracy: 0.9507
Epoch 9/50
60000/60000 [==============================] - 2s 31us/step - loss: 0.1610 - accuracy: 0.9546
Epoch 10/50
60000/60000 [==============================

#### Q6:
Please print the training and testing accuracy.